[package]
name = "plt-rs"
version = "0.1.0"
edition = "2021"
authors = ["ohchase"]
license = "MIT"
description = "Library for iterating and hooking linux and android applications PLT (Procedure Linkage Table) at runtime"
documentation = "https://docs.rs/plt-rs"
readme = "README.md"
repository = "https://github.com/ohchase/plt-rs/"
homepage = "https://github.com/ohchase/plt-rs/"
keywords = ["hacking", "linux", "android", "reversing", "plt", "elf", "bionic", "linkmap"]
exclude = ["/examples", "/templates"]

[lib]
crate-type = ["lib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.137"
#proc-maps = "0.3.0"
