name: Ci-Build

permissions:
  contents: read

on:
  pull_request:
  push:

jobs:
  test:
    strategy:
      matrix:
        - target: aarch64-linux-android
        - target: armv7-linux-androideabi
        - target: x86_64-linux-android
        - target: i686-linux-android
        
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          # (required) Comma-separated list of binary names (non-extension portion of filename) to build and upload.
          # Note that glob pattern is not supported yet.
          bin: libmcbe_r
          # (optional) Target triple, default is host triple.
          target: ${{ matrix.target }}
          # (required) GitHub token for uploading assets to GitHub Releases.
          token: ${{ secrets.TOKEN }}
